//FOR LOOP

// for(let index=0;index<5;index++)
// {
//     console.log("Radha",index);
// }


// for(let index=0;index<5;index=index+2)
// {
//     console.log("Radha",index);
// }

// for(let index=0;index<5;index+=2)
// {
//     console.log("Radha",index);
// }


//WHILE LOOP

// let index =0;
// while(index<5)
// {
//     console.log("Radha");
//     index++;
// }


//do while loop

let index2 = 0;
// do{
//     console.log("Radha");
//     index2++;
// }
// while(index2<5)


// do{
//     console.log("Radha",index2);
//     index2++;
//     if(index2==3)
//     {
//         break;
//     }
// }
// while(index2<5)


do{
    index2++;
    if(index2==3)
    {
        break;
    }
    console.log("Radha",index2);
}
while(index2<5)


let index3 = 10
do{
    index3++;
    if(index3==13)
    {
        continue;
    }
    console.log("Radha",index3);
}
while(index3<15)